### ISSUE TITLE
Implementation of uncertainty prediction module

### ISSUE THREAD

**Issue by charmeleonz** [OpenSpaceAI/Nesie#1]
Hi, may I ask where is the uncertainty prediction module (Equation 3 in paper) implemented in the code? Thanks.

**Comment by Chuxwa** [comment]
I think the code you want might be here. 
https://github.com/OpenSpaceAI/Nesie/blob/395d6da57769dedd192e562839079a06950e9727/mmdet3d/models/dense_heads/side_pooling_module.py#L318
